### ISSUE TITLE
Text language doesn't update

### ISSUE THREAD

**Issue by Aitornado8** [Kruger0/Localize#1]
Hello, I'm testing your Localize script because it looks really really good! 
I had a problem while trying to make it work, I tried to translate the main menu texts and Idk why but the texts doesn't update.
This is a video I recorded while testing.
https://drive.google.com/file/d/1sv9i4UrPPFac6QWuDZBBO1Uzz2TW6DkQ/view?usp=sharing

**Comment by Kruger0** [comment]
Hi! Thanks for the repport. Just to be sure, is this the correct video? Looks like the same one I posted on the Discord Channel... If you could send the video of the issue I would apreciate!

Btw be sure that you're using YOUR sheet url ID, as the one hardcoded in the asset is the demo sheet.

**Comment by Aitornado8** [comment]
Oh shit sorry I'm pretty tired lol
https://drive.google.com/file/d/1goJaRBG5LtZLN_5Ld25_G2p69gU0DYCP/view?usp=sharing here is the video, also yeah I'm using my own sheet ID

**Comment by Kruger0** [comment]
Ohh I see. What I think is happening is that you're storing the translated value in the create event, so it doesn't become aware of the language change. You should rather use the `localize()` function in the draw event it will be aways listening to language changes!
